### ISSUE TITLE
`local.properties` file on version control

### ISSUE THREAD

**Issue by jacobmanning** [chrisgardiner/testRepo#1]
Hello,

I just found this nifty project and would like to use it. However, I am concerned that the `local.properties` file specifically states:

> This file should *NOT* be checked into Version Control Systems

Who knows what could happen now that @chrisgardiner has checked the `local.properties` file into the GitHub version control system.

Any help you could provide would be very helpful.

Thank you.

**Comment by chrisgardiner** [comment]
Hi Jacob,

Thank you for bringing this to my attention. You should find that in the coming hours major changes will be made to this repository, and some of those will solve this problem. I do appreciate you bringing it to my attention, and I will make sure I do not mistakenly commit any more <i>dangerous</i> files again.

You're welcome.
